### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by forestzhang945** [UltimateHackers/Cloak#2]
Traceback (most recent call last):
  File "striker.py", line 220, in <module>
    nmap(ip_addr)
  File "striker.py", line 139, in nmap
    result = br.open(port).read()
  File "/usr/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 203, in open
![20180102113227](https://user-images.githubusercontent.com/9585063/34473682-b45b1006-efb0-11e7-9981-b0ee536ff128.png)

**Comment by s0md3v** [comment]
This bug is not related to Cloak.
If you find something in **Cloak.py** let me know.
Regards.
